AppBundle\Entity\OAuth\AccessToken:
    type: entity
    table: oauth_access_token
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        client:
            targetEntity: AppBundle\Entity\OAuth\Client
            joinColumn:
                nullable: false
        user:
            targetEntity: AppBundle\Entity\ApiUser
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
